"""initial setup

Revision ID: ffe26f2ea025
Revises: 6da360f94088
Create Date: 2020-12-05 21:47:19.609646+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe26f2ea025'
down_revision = '6da360f94088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
