name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update ubuntu
        run: sudo apt-get update -y

      - name: Get latest tag
        id: latesttag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: docker-build
        run: ./scripts/docker-build.sh

      - name: docker push latest and latest version
        run: |
          IMAGE_VERSION="${{ steps.latesttag.outputs.latest_tag }}" ./scripts/docker-push.sh
          IMAGE_VERSION="latest" ./scripts/docker-push.sh
